name: CI

on:
  pull_request:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Docker
        run: |
          docker version
          docker info  

      - name: Setup
        run: |
          python3 dev_setup.py setup

      - name: Tests
        run: docker compose exec clients python3 -m pytest -v --color=yes
